# SCRIPT DE RENOMMAGE DES 118 IMAGES
# Usage : Placer toutes les images dans un même dossier, puis exécuter ce script depuis ce dossier
# PowerShell : cd "C:\chemin\vers\images" puis .\renommer_images.ps1

$mapping = @{
    "J1_01_adam_harishon.png" = "001_adam_harishon.png"
    "J1_02_noah.png" = "002_noah.png"
    "J1_03_avraham_avinou.png" = "003_avraham_avinou.png"
    "J1_04_sarah_imenou.png" = "004_sarah_imenou.png"
    "J1_05_yitshak_avinou.png" = "005_yitshak_avinou.png"
    "J1_06_rivka_imenou.png" = "006_rivka_imenou.png"
    "J1_07_yaakov_avinou.png" = "007_yaakov_avinou.png"
    "J1_08_rahel_lea.png" = "008_rahel_et_lea.png"
    "J1_09_yossef_hatsadik.png" = "009_yossef_hatsadik.png"
    "J1_10_yehouda.png" = "010_yehouda.png"
    "J1_11_moshe_rabbenou.png" = "011_moshe_rabbenou.png"
    "J1_12_aharon_hakohen.png" = "012_aharon_hacohen.png"
    "J1_13_myriam_hanevia.png" = "013_myriam_hanevia.png"
    "pinhas.png" = "014_pinhas.png"
    "J1_14_yehoshoua_bin_noun.png" = "015_yehoshoua.png"
    "calev.png" = "016_calev.png"
    "J1_16_deborah.png" = "017_deborah.png"
    "J1_18_shimshon.png" = "018_shimshon.png"
    "ruth.png" = "019_ruth.png"
    "J1_19_shmouel_hanavi.png" = "020_shmouel_hanavi.png"
    "hanna.png" = "021_hanna.png"
    "J1_20_david_hamelekh.png" = "022_david_hamelekh.png"
    "J1_21_shlomo_hamelekh.png" = "023_shlomo_hamelekh.png"
    "J1_22_eliyahou_hanavi.png" = "024_eliyahou_hanavi.png"
    "J1_17_elisha_hanavi.png" = "025_elisha.png"
    "J1_23_yechayahou.png" = "026_yeshayahou.png"
    "osée.png" = "027_osee.png"
    "amos.png" = "028_amos.png"
    "J1_24_yirmeyahou.png" = "029_yirmeyahou.png"
    "yona.png" = "030_yona.png"
    "J1_25_yehezkel.png" = "031_yehezkel.png"
    "J1_26_daniel.png" = "032_daniel.png"
    "J1_27_ezra_nehemie.png" = "033_ezra_hasofer.png"
    "nehemie.png" = "034_nehemia.png"
    "J1_15_esther_hamalkah.png" = "035_esther_hamalka.png"
    "J2_01_shimon_hatsadik.png" = "036_shimon_hatsadik.png"
    "J2_02_antigone_de_sokho.png" = "037_antigone_de_sokho.png"
    "J2_03_hillel_hazaken.png" = "038_hillel_hazaken.png"
    "J2_04_shammai_hazaken.png" = "039_shammai_hazaken.png"
    "J2_05_rabban_gamliel.png" = "040_rabban_gamliel.png"
    "J2_06_rabbi_yohanan_ben_zakkai.png" = "041_yohanan_ben_zakkai.png"
    "J2_17_rabbi_hanina_ben_dossa.png" = "042_hanina_ben_dossa.png"
    "J2_07_rabbi_eliezer_ben_hyrcanos.png" = "043_eliezer_ben_hyrcanos.png"
    "J2_08_rabbi_yehoshoua_ben_hanania.png" = "044_yehoshoua_ben_hanania.png"
    "J2_09_rabbi_akiva.png" = "045_rabbi_akiva.png"
    "J2_10_rabbi_tarfon.png" = "046_rabbi_tarfon.png"
    "J2_11_rabbi_ishmael.png" = "047_rabbi_ishmael.png"
    "J2_21_shimon_bar_kochba.png" = "048_bar_kokhba.png"
    "J2_12_rabbi_meir.png" = "049_rabbi_meir.png"
    "J2_15_brouria.png" = "050_brouria.png"
    "J2_13_rabbi_shimon_bar_yohai.png" = "051_shimon_bar_yohai.png"
    "J2_14_rabbi_yehouda_bar_ilai.png" = "052_yehouda_bar_ilai.png"
    "J2_16_rabbi_yehouda_hanassi.png" = "053_yehouda_hanassi.png"
    "J2_23_rav_abba_arikha.png" = "054_rav_abba_arikha.png"
    "J2_24_shmouel.png" = "055_mar_shmouel.png"
    "J2_18_rabbi_yohanan.png" = "056_rabbi_yohanan.png"
    "J2_19_reish_lakish.png" = "057_reish_lakish.png"
    "J2_20_rabbi_yehoshoua_ben_levi.png" = "058_yehoshoua_ben_levi.png"
    "eleazar ben pedat.png" = "059_eleazar_ben_pedat.png"
    "J2_22_rabbi_abbahou.png" = "060_rabbi_abbahou.png"
    "J2_26_abbaye.png" = "061_abbaye.png"
    "J2_25_rava.png" = "062_rava.png"
    "J2_27_ravina_rav_ashi.png" = "063_ravina_rav_ashi.png"
    "J3_01_saadia_gaon.png" = "064_rav_saadia_gaon.png"
    "J3_03_rav_sherira_gaon.png" = "065_rav_sherira_gaon.png"
    "J3_02_rav_hai_gaon.png" = "066_rav_hai_gaon.png"
    "J3_14_rabbenou_guershom.png" = "067_rabbenou_guershom.png"
    "J3_12_rachi.png" = "068_rachi.png"
    "J3_13_rabbenou_tam.png" = "069_rabbenou_tam.png"
    "J3_26_ibn_paquda.png" = "070_bahya_ibn_paquda.png"
    "J3_04_ibn_gabirol.png" = "071_shlomo_ibn_gabirol.png"
    "J3_05_yehouda_halevi.png" = "072_yehouda_halevi.png"
    "J3_06_ibn_ezra.png" = "073_avraham_ibn_ezra.png"
    "J3_16_radak.png" = "074_radak.png"
    "J3_07_rambam.png" = "075_maimonide.png"
    "J3_08_ramban.png" = "076_ramban.png"
    "J3_15_rokeach.png" = "077_rokeah.png"
    "J3_09_rabbi_yona_de_gerone.png" = "078_yona_de_gerone.png"
    "J3_10_rashba.png" = "079_rashba.png"
    "J3_22_ralbag.png" = "080_ralbag.png"
    "J3_17_le_rif.png" = "081_rif.png"
    "J3_11_meiri.png" = "082_meiri.png"
    "J3_18_le_rosh.png" = "083_rosh.png"
    "J3_19_le_tur.png" = "084_le_tour.png"
    "J4_04_yossef_karo.png" = "085_yossef_karo.png"
    "J3_21_le_rama.png" = "086_rama.png"
    "J3_23_abravanel.png" = "087_abravanel.png"
    "J3_25_sforno.png" = "088_sforno.png"
    "J3_24_maharal_de_prague.png" = "089_maharal_de_prague.png"
    "J3_27_kli_yakar.png" = "090_kli_yakar.png"
    "J4_02_ramak_cordovero.png" = "091_ramak.png"
    "J4_01_ari_zal.png" = "092_ari_zal.png"
    "J4_03_haim_vital.png" = "093_haim_vital.png"
    "J4_23_Or_HaHaim_HaKadosh.png" = "094_or_hahaim_hakadosh.png"
    "J4_16_ramhal.png" = "095_ramhal.png"
    "J4_05_baal_shem_tov.png" = "096_baal_shem_tov.png"
    "J4_06_maguid_mezeritch.png" = "097_maguid_mezeritch.png"
    "J4_10_elimelekh_lyzhansk.png" = "098_elimelekh_lizhensk.png"
    "J4_09_levi_yitshak_berditchev.png" = "099_levi_yitshak_berditchev.png"
    "J4_07_nahman_breslev.png" = "100_nahman_breslev.png"
    "J4_08_shneur_zalman.png" = "101_shneur_zalman.png"
    "J4_20_rabbi_loubavitch.png" = "102_rabbi_loubavitch.png"
    "J4_11_gaon_vilna.png" = "103_gaon_vilna.png"
    "J4_12_haim_volozhin.png" = "104_haim_volozhin.png"
    "J4_15_israel_salanter.png" = "105_israel_salanter.png"
    "J4_13_hafets_haim.png" = "106_hafets_haim.png"
    "J4_14_hazon_ish.png" = "107_hazon_ish.png"
    "J4_17_hatam_sofer.png" = "108_hatam_sofer.png"
    "J4_24_rav_hirsch.png" = "109_samson_raphael_hirsch.png"
    "J4_23_sarah_schenirer.png" = "110_sarah_schenirer.png"
    "J4_18_rav_kook.png" = "111_rav_kook.png"
    "J4_25_rav_tsvi_kook.png" = "112_rav_tsvi_kook.png"
    "Rav_Moshe_Feinstein.png" = "113_moshe_feinstein.png"
    "J4_19_rav_soloveitchik.png" = "114_rav_soloveitchik.png"
    "J4_26_nechama_leibowitz.png" = "115_nechama_leibowitz.png"
    "J4_21_rav_ovadia_yossef.png" = "116_rav_ovadia_yossef.png"
    "J4_22_rav_steinsaltz.png" = "117_rav_steinsaltz.png"
    "J4_27_jonathan_sacks.png" = "118_jonathan_sacks.png"
}

$renamed = 0
$notfound = 0

foreach ($entry in $mapping.GetEnumerator()) {
    $src = $entry.Key
    $dst = $entry.Value
    if (Test-Path $src) {
        Rename-Item -Path $src -NewName $dst
        Write-Host "OK  $src -> $dst" -ForegroundColor Green
        $renamed++
    } else {
        Write-Host "!!  $src NON TROUVE" -ForegroundColor Red
        $notfound++
    }
}

Write-Host ""
Write-Host "============================================"
Write-Host "Renommes : $renamed / 118"
Write-Host "Non trouves : $notfound"
Write-Host "============================================"
